import { SessionsServices } from "../../src/services/sessions.services.js";
import { faker } from "@faker-js/faker";
import { hash } from "../../src/utils/hash.js";

const mockUser = {
  email: "correctEmail",
  password: hash("correctPassword"),
};

const mockUsers = [];
for (let i = 0; i < 100; i++) {
  mockUsers.push({
    email: faker.internet.email(),
  });
}

const usersDaoMock = {
  create: async ({ email }) => {
    if (email === "AlreadyExist") {
      return Promise.reject(new Error("DUPLICATE"));
    }
    return mockUser;
  },
  findOne: async ({ email }) => {
    if (email === "correctEmail") {
      return mockUser;
    }
    return Promise.reject(new Error("NOT FOUND"));
  },
  readMany: async ({}) => {
    return mockUsers;
  },
};

const sessionsServices = new SessionsServices(usersDaoMock);

async function testRegisterWithoutUserNameFail() {
  const credentials = {
    email: "",
    password: "correctPassword",
  };

  let errorMessage;

  try {
    await sessionsServices.register(credentials,"local");
    throw new Error("‚ùå deberia haber lanzado un error pero no lo lanz√≥");
  } catch (error) {
    errorMessage = error.message;
  }

  if (errorMessage === "Authentication Error - Please Check your credentials") {
    console.log("üëç testRegisterWithoutUserNameFail")
  } else {
    console.log(
      "‚ùå el error no es el esperado. se lanz√≥ el siguiente error: " + errorMessage
    );
  }
}

async function testRegisterWithoutPasswordFail() {
  const credentials = {
    email: "correctEmail",
    password: "",
  };

  let errorMessage;
describe("api",()=>{})
  try {
    await sessionsServices.register(credentials,"local");
    throw new Error("‚ùå deberia haber lanzado un error pero no lo lanz√≥");
  } catch (error) {
    errorMessage = error.message;
  }

  if (errorMessage === "Authentication Error - Please Check your credentials") {
    console.log("üëç testRegisterWithoutPasswordFail")
  } else {
    console.log(
      "‚ùå el error no es el esperado. se lanz√≥ el siguiente error: " + errorMessage
    );
  }
}

async function testRegisterWithDuplicatedEmailFail() {
  const credentials = {
    email: "AlreadyExist",
    password: "correctPassword",
  };

  let errorMessage;

  try {
    await sessionsServices.register(credentials,"local");
    throw new Error("‚ùå deberia haber lanzado un error pero no lo lanz√≥");
  } catch (error) {
    errorMessage = error.message;
  }

  if (errorMessage === "DUPLICATE") {
    console.log("üëç testRegisterWithDuplicatedEmailFail")
  } else {
    console.log(
      "‚ùå el error no es el esperado. se lanz√≥ el siguiente error: " + errorMessage
    );
  }
}

async function testLoginWithoutUserNameFail() {
  const credentials = {
    email: "",
    password: "correctPassword",
  };

  let errorMessage;

  try {
    await sessionsServices.login(credentials);
    throw new Error("‚ùå deberia haber lanzado un error pero no lo lanz√≥");
  } catch (error) {
    errorMessage = error.message;
  }

  if (errorMessage === "Authentication Error - Please Check your credentials") {
    console.log("üëç testLoginWithoutUserNameFail")
  } else {
    console.log(
      "‚ùå el error no es el esperado. se lanz√≥ el siguiente error: " + errorMessage
    );
  }
}

async function testLoginWithoutPasswordFail() {
  const credentials = {
    email: "correctEmail",
    password: "",
  };

  let errorMessage;

  try {
    await sessionsServices.register(credentials);
    throw new Error("‚ùå deberia haber lanzado un error pero no lo lanz√≥");
  } catch (error) {
    errorMessage = error.message;
  }

  if (errorMessage === "Authentication Error - Please Check your credentials") {
    console.log("üëç testLoginWithoutPasswordFail")
  } else {
    console.log(
      "‚ùå el error no es el esperado. se lanz√≥ el siguiente error: " + errorMessage
    );
  }
}

async function testLoginWithWrongEmailFail() {
  const credentials = {
    email: "wrongEmail",
    password: "correctPassword",
  };

  let errorMessage;

  try {
    await sessionsServices.login(credentials);
    throw new Error("‚ùå deberia haber lanzado un error pero no lo lanz√≥");
  } catch (error) {
    errorMessage = error.message;
  }

  if (errorMessage === "NOT FOUND") {
    console.log("üëç testLoginWithWrongEmailFail")
  } else {
    console.log(
      "‚ùå el error no es el esperado. se lanz√≥ el siguiente error: " + errorMessage
    );
  }
}

async function testLoginWithWrongPasswordFail() {
  const credentials = {
    email: "correctEmail",
    password: "wrongPassword",
  };

  let errorMessage;

  try {
    await sessionsServices.login(credentials);
    throw new Error("‚ùå deberia haber lanzado un error pero no lo lanz√≥");
  } catch (error) {
    errorMessage = error.message;
  }

  if (errorMessage === "Authentication Error - Please Check your credentials") {
    console.log("üëç testLoginWithWrongPasswordFail")
  } else {
    console.log(
      "‚ùå el error no es el esperado. se lanz√≥ el siguiente error: " + errorMessage
    );
  }
}

await testRegisterWithoutUserNameFail()
await testRegisterWithoutPasswordFail()
await testRegisterWithDuplicatedEmailFail()
await testLoginWithoutUserNameFail()
await testLoginWithoutPasswordFail()
await testLoginWithWrongEmailFail()
await testLoginWithWrongPasswordFail()

